Update solo clone with build fix (#122)
Updates the `solo` clone to include
https://github.com/AlfioEmanueleFresta/solo/commit/c12e6c7e3c097070100a0713bdf9b9db56f02730.

Fixes an occasional build error building `solo`:

```
  make failed: Output { status: ExitStatus(unix_wait_status(512)), stdout: "cc -O2 -fdata-sections -ffunction-sections -fcommon -g -I../ -I./fido2/ -I./pc -I../pc -I./tinycbor/src -DAES256=1  -DSOLO_EXPERIMENTAL=1 -DDEBUG_LEVEL=1   -c -o pc/device.o pc/device.c\n", stderr: "pc/device.c: In function ‘device_init’:\npc/device.c:256:5: error: too many arguments to function ‘ctap_init’; expected 0, have 1\n  256 |     ctap_init(1);\n      |     ^~~~~~~~~ ~\nIn file included from ./fido2/storage.h:10,\n                 from ./fido2/device.h:10,\n                 from pc/device.c:20:\n./fido2/ctap.h:389:6: note: declared here\n  389 | void ctap_init();\n      |      ^~~~~~~~~\nmake: *** [<builtin>: pc/device.o] Error 1\n" }
```

The root cause is commit
[e8d0ad5e7cf2f8bd5a57aae8e5e8b69d3816474c](https://github.com/AlfioEmanueleFresta/solo/commit/e8d0ad5e7cf2f8bd5a57aae8e5e8b69d3816474c),
part of https://github.com/solokeys/solo1/pull/121, which removes an
extra argument from `ctap_init` but didn't update `pc/device.c`.

Note upstreaming PR has been blocked for a while -
https://github.com/solokeys/solo1/pull/577. IMO we should eventually
migrate to Solo2, with FIDO2 support, rather than spend more time on
solo1.